Samo/Controllers/ServersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Samo.Data;
using Samo.Models;
using Samo.Areas.Identity;
using Microsoft.AspNetCore.Http;

namespace Samo.Controllers
{
    public class ServersController : Controller
    {
        private readonly SamoContext _context;

        public ServersController(SamoContext context)
        {
            _context = context;
        }

        // GET: Servers
        public async Task<IActionResult> Index(string sortOrder, string DcFilter, int cpuFilter, int ramFilter)
        {
            bool isAdmin = AuthenticationManager.isAdmin(User, _context);
            string username = User.Identity.Name;
            ViewData["CPUSortParam"] = String.IsNullOrEmpty(sortOrder) ? "cpu_desc" : "";
            ViewData["RAMSortParam"] = sortOrder == "ram_desc" ? "ram_asc" : "ram_desc";
            ViewData["OSSortParam"] = sortOrder == "os_desc" ? "os_asc" : "os_desc";
            ViewData["DataCenterSortParam"] = sortOrder == "datacenter_desc" ? "datacenter_asc" : "datacenter_desc";
            ViewData["ramFilter"] = ramFilter;
            ViewData["DcFilter"] = DcFilter;
            ViewData["cpuFilter"] = cpuFilter;

            var samoContext = from s in _context.Servers
                              select s;

            if (string.IsNullOrEmpty(username))
            {
                return View("_NotLoggedIn");
            }
            else if (!isAdmin)
            {
                samoContext = samoContext.Where(s => s.User.UserName == username);
            }


            if (!String.IsNullOrEmpty(DcFilter))
            {
                samoContext = samoContext.Where(s => s.DataCenter.Name.Contains(DcFilter));
            }
            if (cpuFilter > 0)
            {
                samoContext = samoContext.Where(s => s.CPU >= cpuFilter);
            }
            if (ramFilter > 0)
            {
                samoContext = samoContext.Where(s => s.RAM >= ramFilter);
            }

            switch (sortOrder)
            {

                case "cpu_desc":
                    samoContext = samoContext.OrderByDescending(s => s.CPU).Include(s => s.DataCenter).Include(s => s.User);
                    break;
                case "ram_desc":
                    samoContext = samoContext.OrderByDescending(s => s.RAM).Include(s => s.DataCenter).Include(s => s.User);
                    break;
                case "ram_asc":
                    samoContext = samoContext.OrderBy(s => s.RAM).Include(s => s.DataCenter).Include(s => s.User);
                    break;
                case "os_desc":
                    samoContext = samoContext.OrderByDescending(s => s.OS).Include(s => s.DataCenter).Include(s => s.User);
                    break;
                case "os_asc":
                    samoContext = samoContext.OrderBy(s => s.OS).Include(s => s.DataCenter).Include(s => s.User);
                    break;
                case "datacenter_desc":
                    samoContext = samoContext.OrderByDescending(s => s.DataCenter.ID).Include(s => s.DataCenter).Include(s => s.User);
                    break;
                case "datacenter_asc":
                    samoContext = samoContext.OrderBy(s => s.DataCenter.ID).Include(s => s.DataCenter).Include(s => s.User);
                    break;
                default:
                    samoContext = samoContext.OrderBy(s => s.CPU).Include(s => s.DataCenter).Include(s => s.User);
                    break;
            }
            return View(await samoContext.ToListAsync());
        }

        // GET: Servers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            string username = User.Identity.Name;
            if (string.IsNullOrEmpty(username))
            {
                return View("_NotLoggedIn");
            }

            if (id == null)
            {
                return NotFound();
            }

            var server = await _context.Servers.Include(s => s.DataCenter).Include(s => s.DataCenter.Country).Include(s => s.User).FirstOrDefaultAsync(m => m.ID == id);
            if (server == null)
            {
                return NotFound();
            }

            if (!AuthenticationManager.isPermitted(User, server.UserID, _context))
            {
                return View("_UnAuthorized");
            }


            return View(server);
        }

        // GET: Servers/Create
        public IActionResult Create()
        {
            string username = User.Identity.Name;
            if (string.IsNullOrEmpty(username))
            {
                return View("_NotLoggedIn");
            }

            if (getLinuxOrdersCount() >= 2)
            {
                ViewData["LinuxGuide"] = "Hi there! If you need assistance in managing linux system, check this link:";
                ViewData["linuxLink"] = "https://ryanstutorials.net/linuxtutorial/";
            }
            ViewData["DCName"] = new SelectList(_context.DataCenter, "ID", "Name");
            return View();
        }

        // POST: Servers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CPU,RAM,UserID,OS,DataCenterID")] Server server)
        {
            string username = User.Identity.Name;
            if (string.IsNullOrEmpty(username))
            {
                return View("_NotLoggedIn");
            }

            if (server.OS == OS.Linux)
            {
                increaseLinuxCount();
            }

            string currentUserName = User.Identity.Name;
            if (currentUserName == null)
            {
                return View("_NotLoggedIn");
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(u => u.UserName == currentUserName);

            server.UserID = user.Id;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(server);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. " +
            "Try again, and if the problem persists " +
            "see your system administrator.");
                }
            }
            ViewData["DCName"] = new SelectList(_context.DataCenter, "ID", "Name", server.DataCenterID);
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id", server.UserID);
            return View(server);
        }

        // GET: Servers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            string username = User.Identity.Name;
            if (string.IsNullOrEmpty(username))
            {
                return View("_NotLoggedIn");
            }

            if (id == null)
            {
                return NotFound();
            }

            var server = await _context.Servers.SingleOrDefaultAsync(s => s.ID == id);
            if (server == null)
            {
                return NotFound();
            }

            if (!AuthenticationManager.isPermitted(User, server.UserID, _context))
            {
                return View("_UnAuthorized");
            }


            ViewData["DataCenterID"] = new SelectList(_context.DataCenter, "ID", "Name", server.DataCenterID);
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id", server.UserID);
            return View(server);
        }

        // POST: Servers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,CPU,RAM,UserID,OS,DataCenterID")] Server server)
        {
            string username = User.Identity.Name;
            if (string.IsNullOrEmpty(username))
            {
                return View("_NotLoggedIn");
            }

            if (id != server.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(server);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServerExists(server.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DataCenterID"] = new SelectList(_context.DataCenter, "ID", "Name", server.DataCenterID);
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id", server.UserID);
            return View(server);
        }

        // GET: Servers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            string username = User.Identity.Name;
            if (string.IsNullOrEmpty(username))
            {
                return View("_NotLoggedIn");
            }


Samo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Samo Cloud</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SAMO Cloud</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Servers" asp-action="Index">Servers</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>

        <partial name="_CookieConsentPartial" />

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2021 - SAMO Cloud</p>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/dollarRate.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"></script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>
        @RenderSection("Scripts", required: false)
    </body>
</html>

Samo/Views/Shared/_NotLoggedIn.cshtml
<div style="font-size: 29pt;padding: 100px;">
    This action requires you to be logged in :( 
</div>

Samo/Views/Shared/_UnAuthorized.cshtml
<div style="font-size: 29pt;padding: 100px;">
    You are not authorized to perform this action.
</div>