Samo/Controllers/AdminStatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Samo.Data;
using Samo.Models;
using System.Text;
using Samo.Areas.Identity;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Samo.Controllers
{
    public class AdminStatisticsController : Controller
    {
        private readonly SamoContext _context;

        public AdminStatisticsController(SamoContext context)
        {
            _context = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            if (!AuthenticationManager.isAdmin(User, _context))
                return View("_UnAuthorized");
            return View();
        }

        public JsonResult OSCountStats()
        {
            List<OsCountData> stats = new List<OsCountData>();
            var data = _context.Servers.GroupBy(s => s.OS);
            foreach (var os in data)
            {
                stats.Add(new OsCountData(){Name = os.Key.ToString(),Count = os.Count()});
            }

            return Json(stats);

        }

        public JsonResult ServersPerUser()
        {
            List<UserServerData> stats = new List<UserServerData>();
            var data = _context.Servers.Include(s => s.User).ToList().GroupBy(s => s.User);

            foreach (var user in data)
            {
                stats.Add(new UserServerData{User = user.Key.UserName,Count = user.Count()});
            }
            return Json(stats);
        }

        public JsonResult ServerPerDC()
        {
            List<DatacenterData> stats = new List<DatacenterData>();
            var data = _context.Servers.Include(s => s.DataCenter).ToList().GroupBy(s => s.DataCenter);

            foreach (var datacenter in data)
            {
                stats.Add(new DatacenterData{Name = datacenter.Key.Name,Count = datacenter.Count()});
            }
            return Json(stats);
        }
    }

    public class DatacenterData
    {
        public string Name { get; set; }
        public int Count { get; set; }
    }

    public class UserServerData
    {
        public string User { get; set; }
        public int Count { get; set; }
    }

    public class OsCountData
    {
        public string Name { get; set; }
        public int Count { get; set; }
    }
}

Samo/Controllers/DataCentersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Samo.Data;
using Samo.Models;
using Samo.Areas.Identity;

namespace Samo.Controllers
{
    public class DataCentersController : Controller
    {
        private readonly SamoContext _context;

        public DataCentersController(SamoContext context)
        {
            _context = context;
        }

        // GET: DataCenters
        public async Task<IActionResult> Index(string countryFilter, string nameFilter)
        {
            if (!AuthenticationManager.isAdmin(User, _context))
                return View("_UnAuthorized");
            ViewData["countryFilter"] = countryFilter;
            ViewData["nameFilter"] = nameFilter;

            var dataCenter =  _context.DataCenter.Include(d => d.Country);

            var samoContext = from s in dataCenter select s;

            if (!String.IsNullOrEmpty(countryFilter))
                samoContext = samoContext.Where(s => s.Country.Name.Contains(countryFilter));
            if (!String.IsNullOrEmpty(nameFilter))
                samoContext = samoContext.Where(s => s.Name.Contains(nameFilter));


            return View(await samoContext.ToListAsync());
        }

        // GET: DataCenters/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (!AuthenticationManager.isAdmin(User, _context))
                return View("_UnAuthorized");
            if (id == null)
                return NotFound();

            var dataCenter = await _context.DataCenter.Include(d => d.Country).FirstOrDefaultAsync(m => m.ID == id);
            
            if (dataCenter == null)
                return NotFound();

            return View(dataCenter);
        }

        // GET: DataCenters/Create
        public IActionResult Create()
        {
            if (!AuthenticationManager.isAdmin(User, _context))
                return View("_UnAuthorized");

            ViewData["CountryName"] = new SelectList(_context.Country, "ID", "Name");

            return View();
        }

        // POST: DataCenters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,CountryID")] DataCenter dataCenter)
        {
            var isDataCenterExistInCountry =  _context.DataCenter.Any(d => d.CountryID == dataCenter.CountryID);

            if (isDataCenterExistInCountry) {
                ViewData["ErrorMessage"] = "Can't add more than one data center in the same country";
            }

            if (ModelState.IsValid && !isDataCenterExistInCountry)
            {
                _context.Add(dataCenter);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            ViewData["CountryName"] = new SelectList(_context.Country, "ID", "Name", dataCenter.CountryID);

            return View(dataCenter);
        }

        // GET: DataCenters/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (!AuthenticationManager.isAdmin(User, _context))
                return View("_UnAuthorized");
            if (id == null)
                return NotFound();

            var dataCenter = await _context.DataCenter.FindAsync(id);
            if (dataCenter == null)
                return NotFound();

            ViewData["CountryName"] = new SelectList(_context.Country, "ID", "Name");

            return View(dataCenter);
        }

        // POST: DataCenters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,Name,CountryID")] DataCenter dataCenter)
        {
            if (id != dataCenter.ID)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dataCenter);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DataCenterExists(dataCenter.ID))
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["CountryName"] = new SelectList(_context.Country, "ID", "Name", dataCenter.CountryID);

            return View(dataCenter);
        }

        // GET: DataCenters/Delete/5
        public async Task<IActionResult> Delete(string id, bool? saveChangesError = false)
        {
            if (!AuthenticationManager.isAdmin(User, _context))
                return View("_UnAuthorized");
            if (id == null)
                return NotFound();

            var dataCenter = await _context.DataCenter.Include(d => d.Country).FirstOrDefaultAsync(m => m.ID == id);
            if (dataCenter == null)
                return NotFound();

            if (saveChangesError.GetValueOrDefault())
                ViewData["ErrorMessage"] = "The deletion failed. Contact the administrator please.";

            return View(dataCenter);
        }


        // POST: DataCenters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var dataCenter = await _context.DataCenter.FindAsync(id);
            _context.DataCenter.Remove(dataCenter);
            try
            {
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }

        }

        private bool DataCenterExists(string id)
        {
            return _context.DataCenter.Any(e => e.ID == id);
        }
    }
}

Samo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Samo.Models;
using Samo.Data;
using Samo.Areas.Identity;

namespace Samo.Controllers
{
    public class HomeController : Controller
    {
        private readonly SamoContext _context;

        public HomeController(SamoContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewData["isAdmin"] = AuthHelper.isAdmin(User, _context);
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Samo/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Samo.Data;
using Samo.Models;
using Microsoft.AspNetCore.Identity;


namespace Samo.Controllers
{
    public class UsersController : Controller
    {
        private readonly SamoContext _context;

        public UsersController(SamoContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index(string partialId, string partialName, string IsAdmin)
        {
            ViewData["IsAdminFilter"] = IsAdmin;
            ViewData["NameFilter"] = partialName;
            ViewData["IdFilter"] = partialId;
            
            var UsersList = from u in _context.Users
                            select u;

            if (!String.IsNullOrEmpty(partialId))
            {
                UsersList = UsersList.Where(u => u.Id.Contains(partialId));
            }
            if (!String.IsNullOrEmpty(partialName))
            {
                UsersList = UsersList.Where(u => u.UserName.Contains(partialName));
            }
            if (IsAdmin == "Admin")
            {
                UsersList = UsersList.Where(u => u.isAdmin == true);
            }
            if (IsAdmin == "User")
            {
                UsersList = UsersList.Where(u => u.isAdmin == false);
            }

            return View(await UsersList.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
                return NotFound();

            var user = await _context.Users.FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
                return NotFound();

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Country,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
                return NotFound();

            var user = await _context.Users.FindAsync(id);
            if (user == null)
                return NotFound();
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Country,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] User user)
        {
            if (id != user.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string id, bool? saveChangesError = false)
        {
            if (id == null)
                return NotFound();

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
                return NotFound();

            if (saveChangesError.GetValueOrDefault())
                ViewData["ErrorMessage"] = "The user has active servers and cannot be deleted.";

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {

            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            try
            {
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
        }

        private bool UserExists(string userId)
        {
            return _context.Users.Any(e => e.Id == userId);
        }
    }
}

Samo/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<body>
    <h1 id="header">Our SAMO Cloud</h1>
    <div id="tran"></div>
    <h1>   </h1>
    <div id="mul">
        Our product "SAMO Cloud" is the best in the market
        It is for those who want to get a server easy and fast
        We welcome you to use our cloud and enjoy the exprience
    </div>
    <br />
    <br />

    <div id="video" text-align="center">
        <video width="400" height="300" controls style="display:block; margin: 0 auto;" autoplay>
            <source src="~/videos/DCVideo.mp4" type="video/mp4">
        </video>
    </div>
</body>

Samo/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Samo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<link rel="stylesheet" href="/css/tweets.css">

@if ((bool)ViewData["isAdmin"] == true)
{

<div>
    <h2> Hello admin!</h2>
    <br />

    <table style="width:60%">
        <tr>
            <td>
                <a class="adminoption" class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Manage application Users</a>
            </td>
            <td>
                <a class="adminoption" class="nav-link text-dark" asp-area="" asp-controller="DataCenters" asp-action="Index">Manage Data Centers</a>
            </td>
            <td>
                <a class="adminoption" class="nav-link text-dark" asp-area="" asp-controller="AdminStatistics" asp-action="Index">View system statistics</a>
            </td>
        </tr>
    </table>
    </div>

}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/first.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Start Building on SAMO Cloud Today!
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/second.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Explore Our Products
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/third.jpg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Powering Customer Innovation
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>

</div>

<div>
    <img id="twitter" src="~/images/twitter.png" hidden />
    <p align="center">
        <canvas id="tweeterlogo" width="128" height="128"></canvas>
    </p>

</div>
<h4 style="text-align:center;">Linux related Tweets:</h4>
<aside id="tweetArea"></aside>
@section Scripts {
    <script src="~/js/tweetsIntegration.js"></script>
}